--liquibase formatted sql
--changeset <Serhii Buria>:<add-data-table-products>
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Молоко', 850, 28, 'https://i.ibb.co/TMmdFTh/Milk.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мята', 50, 48, 'https://i.ibb.co/h7nWjnH/Mint.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Олія оливкова', 500, 132, 'https://ibb.co/QYsZyc0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелений горох', 250, 228, 'https://i.ibb.co/8PFJ1Bk/Olive-oil.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Базилік', 50, 48, 'https://i.ibb.co/ZMF2cWH/Basil.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Дріжджі', 22, 21, 'https://i.ibb.co/zm8FF8G/Yeast.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цибуля порей', 100, 18, 'https://i.ibb.co/HBNxWj8/Leeks.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимонний сік', 200, 30, 'https://i.ibb.co/9HWFM9c/Juice-lime.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шпроти', 190, 74, 'https://i.ibb.co/VC0vrys/Sprats.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оливи зелені без кісточок', 300, 62, 'https://i.ibb.co/X7xkQxR/Olives.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горіх волоський', 150, 169, 'https://i.ibb.co/1KShh7T/Walnut.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорнослив', 250, 215, 'https://i.ibb.co/10yCZvV/Prunes.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Буряк', 500, 8, 'https://i.ibb.co/vzD1QZF/beetroot.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа кукурудзяна', 1000, 16, 'https://i.ibb.co/zNzjDx0/corn-grits.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бекон', 450, 140, 'https://i.ibb.co/XJjRKV8/becon.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бринза', 230, 54, 'https://i.ibb.co/yhJQd65/cheese.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Апельсин', 1000, 50, 'https://i.ibb.co/yWzrtFM/apelsin.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бальзамічний оцет', 500, 139, 'https://i.ibb.co/5xbCbs9/c6b92f80-6492-11eb-a219-15b5009231c3-jpg.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Баранина', 1000, 162, 'https://i.ibb.co/K0H62wy/ec9514f9546ac5f8c93949c0340f1a41.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Ванільний екстракт', 30, 160, 'https://i.ibb.co/c8Hdr6P/2023-04-20-21-00.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершки 10%', 500, 40, 'https://i.ibb.co/Gkr9BwH/2582308.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершкове масло', 200, 58, 'https://i.ibb.co/1MYNTjs/original-1459294392-68319296836853.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вишня (з кісточками)', 100, 55, 'https://i.ibb.co/qRD5NNh/2023-04-20-20-54.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вода', 20, 80, 'https://i.ibb.co/n1QSBky/img-276443-1617366179-6892.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Гарбузове насіння', 500, 159, 'https://i.ibb.co/7j7zmjT/2023-04-20-20-50.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горох', 900, 15, 'https://i.ibb.co/JxB9MMJ/33280-4820015739988.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Густий натуральний йогурт', 300, 25, 'https://i.ibb.co/N64GJb9/00-00000062-grecheskij-jogurt-naturalnyj-10-tm-mlekovita-1kg.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень', 100, 74, 'https://i.ibb.co/3fDT7C4/fresh-herbs-dill-parsley-spinach-911453.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень (кріп)', 100, 64, 'https://i.ibb.co/44zw37y/krip-zelen-sushena-40g.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Капуста', 1000, 22, 'https://i.ibb.co/7Ykk7FJ/kapusta-moloda.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Квашена капуста', 500, 46, 'https://i.ibb.co/tMKML8D/f32eb011-dee1-d301-db4d-a67362876c2f.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кисло-солодкий соус', 320, 126, 'https://i.ibb.co/tMKML8D/f32eb011-dee1-d301-db4d-a67362876c2f.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крохмаль', 230, 65,'https://i.ibb.co/10pmKtL/image-9b4d2000-a4d4-11ea-81fa-002590ebb0db.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Малина', 500, 98, 'https://i.ibb.co/bP6VGKG/malina-1-1.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мед', 500, 116, 'https://i.ibb.co/6g4KZxm/c1863726db4cf1dc62b0453d4dfe8f03.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Морква', 1000, 60, 'https://i.ibb.co/jL10h9M/94fba553-e17a-48e1-b0e9-1f708c65d307.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мясо ягняти', 1000, 160, 'https://i.ibb.co/sRsMngx/05-8-jpg-pagespeed-ce-a-ZXEl3al-Ud.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Насіння льону', 100, 9, 'https://i.ibb.co/qjsc0jq/nasinnja-lonu-640x640.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Огірки', 1000, 109, 'https://i.ibb.co/XJKQLbw/d8c445f1-5ce6-11e9-b2d2-000c2974779c.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оцет', 1000, 29, 'https://i.ibb.co/68rhjMh/02f158b0-6498-11eb-ac63-772bd181f15b-jpg.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Паста', 500, 51, 'https://i.ibb.co/yW2StKk/izdeliya-makaronnye-la-pasta-perfetto-stortelli.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець солодкий', 1000, 230, 'https://i.ibb.co/tDhh7mm/Bell-Peppers.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець чилі', 100, 34, 'https://i.ibb.co/MnQxDdp/2023-04-20-20-07.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Полуниця', 250, 50, 'https://i.ibb.co/n1C3Yp1/klubnika-egipet-73107014367685.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Помідори', 1000, 77, 'https://i.ibb.co/7nFSS4S/image-of-hot-house-red-cluster-tomatoes-fruit-14764460834860-600x600.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Пшоно', 1000, 27, 'https://i.ibb.co/j4sBV0B/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Рис', 800, 79, 'https://i.ibb.co/3Tm1sk4/2023-04-20-19-58.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розмарин', 70, 32, 'https://i.ibb.co/2cP5VKQ/4088600212500-0.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розпушувач тіста', 12, 6, 'https://i.ibb.co/njBLt75/49001-003.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Свинина', 1000, 120, 'https://i.ibb.co/LYhDxmT/marbled-pig-meat-pork-loin-slices.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Смалець', 100, 7, 'https://i.ibb.co/NTsSpkh/smalec-spichlerz-rusiecki-staropolskij-s-myasom.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сода', 300, 19, 'https://i.ibb.co/LSWGSrS/soda-pishchevaya-04kg-ukraina0-1.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сухарики', 400, 123, 'https://i.ibb.co/K5jpwLx/68f1b009.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тимʼян', 60, 28, 'https://i.ibb.co/rQTm9Zc/2023-04-20-19-10-1.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Томатна паста',460, 83, 'https://i.ibb.co/bzNJkm0/tomatna-pata.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Фарш', 500, 89, 'https://i.ibb.co/pxb10jT/GF-Mince-Beef-web1.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукор', 1000, 34, 'https://i.ibb.co/dBj5zmR/catalog-product-main-18505.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукрова пудра', 80, 19, 'https://i.ibb.co/nwbZmkF/ae4c3ed8-bae9-11ec-ad16-000c2974779c-912x804-f.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорниця', 500, 177, 'https://i.ibb.co/wrGj1R8/95a21fc78dcdc137c3b75bc8bfb3461c.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шампіньйони', 250, 42, 'https://i.ibb.co/cvFnZzP/shampwhite.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яловичина', 1000, 190, 'https://i.ibb.co/mrj5fN9/4d7a829c-7d28-11e9-af5f-000c2974779c-912x804-f.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Хрін свіжий', 500, 180, 'https://i.ibb.co/YtPH4Tq/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чебрець', 230, 66, 'https://i.ibb.co/Y7vzKsp/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Творог', 350, 54, 'https://i.ibb.co/tHgrct0/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа манна', 550, 72, 'https://i.ibb.co/1dSWDQN/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оселедець', 500, 98, 'https://i.ibb.co/Tb287Vv/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яблука', 1000, 29, 'https://i.ibb.co/y6kJGzk/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мідії', 1000, 80, 'https://i.ibb.co/jgVLTrm/2.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вино біле столове ', 750, 99, 'https://i.ibb.co/cF2chzL/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Судак свіжий', 1000, 69, 'https://i.ibb.co/v3mBQbN/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Куркума', 300, 85, 'https://i.ibb.co/Kqvt7Xf/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лавровий лист', 20, 15, 'https://i.ibb.co/smJdYkw/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимон', 1000, 49, 'https://i.ibb.co/3YK2PrP/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кориця', 100, 34, 'https://i.ibb.co/XJpYtgq/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мускатний горіх', 10, 9, 'https://i.ibb.co/KwG2KWM/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тісто листкове', 900, 68, 'https://i.ibb.co/my5WkfX/image.jpg');


