--liquibase formatted sql
--changeset <Serhii Buria>:<add-data-table-products>
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Молоко', 850, 28, 'https://ibb.co/fd4LPS0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мята', 50, 48, 'https://ibb.co/kHr8fr0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Олія оливкова', 500, 132, 'https://ibb.co/QYsZyc0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелений горох', 250, 228, 'https://ibb.co/FW1bH3x');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Базилік', 50, 48, 'https://ibb.co/0G6sYhB');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Дріжджі', 22, 21, 'https://ibb.co/0nBKKBh');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цибуля порей', 100, 18, 'https://ibb.co/Fms0SFT');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимонний сік', 200, 30, 'https://ibb.co/Mk7YXDZ');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шпроти', 190, 74, 'https://ibb.co/c8KNM5j');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оливи зелені без кісточок', 300, 62, 'https://ibb.co/y6FB9Fj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горіх волоський', 150, 169, 'https://ibb.co/vmtggVk');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорнослив', 250, 215, 'https://ibb.co/9pKxn8X');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Буряк', 500, 8, 'https://ibb.co/q1xBWkS');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа кукурудзяна', 1000, 16, 'https://ibb.co/V3sr59P');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бекон', 450, 140, 'https://ibb.co/f0qwyQv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бринза', 230, 54, 'https://ibb.co/7gF1jnV');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Апельсин', 1000, 50, 'https://ibb.co/vZNSp4r');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бальзамічний оцет', 500, 139, 'https://ibb.co/M5FKFPh');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Баранина', 1000, 162, 'https://ibb.co/7YFvn4y');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Ванільний екстракт', 30, 160, 'https://ibb.co/Sm8p3t2');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершки 10%', 500, 40, 'https://ibb.co/vmMhg5X');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершкове масло', 200, 58, 'https://ibb.co/xYKb6dm');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вишня (з кісточками)', 100, 55, 'https://ibb.co/hKgfBBr');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вода', 20, 80, 'https://ibb.co/myh70zK');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Гарбузове насіння', 500, 159, 'https://ibb.co/wBDLmBb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горох', 900, 15, 'https://ibb.co/VHjsPP4');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Густий натуральний йогурт', 300, 25, 'https://ibb.co/JRhSGgv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень', 100, 74, 'https://ibb.co/KNM5Xrb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень (кріп)', 100, 64, 'https://ibb.co/F82kCKv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Капуста', 1000, 22, 'https://ibb.co/6nXX65R');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Квашена капуста', 500, 46, 'https://ibb.co/WW5WVgf');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кисло-солодкий соус', 320, 126, 'https://ibb.co/WW5WVgf');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крохмаль', 230, 65,'https://ibb.co/hgnmHJy');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Малина', 500, 98, 'https://ibb.co/0cnLzGz');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мед', 500, 116, 'https://ibb.co/jgLC52T');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Морква', 1000, 60, 'https://ibb.co/NLHDxgj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мясо ягняти', 1000, 160, 'https://ibb.co/2hcfxFV');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Насіння льону', 100, 9, 'https://ibb.co/LRtcQRj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Огірки', 1000, 109, 'https://ibb.co/2KC9hyb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оцет', 1000, 29, 'https://ibb.co/C6mdRcd');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Паста', 500, 51, 'https://ibb.co/72h4PBp');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець солодкий', 1000, 230, 'https://ibb.co/QMcc2bb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець чилі', 100, 34, 'https://ibb.co/4W3nZkM');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Полуниця', 250, 50, 'https://ibb.co/8xczfkx');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Помідори', 1000, 77, 'https://ibb.co/Vg8LLmL');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Пшоно', 1000, 27, 'https://ibb.co/XJMNy0N');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Рис', 800, 79, 'https://ibb.co/b65137Q');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розмарин', 70, 32, 'https://ibb.co/XFpV0Jg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розпушувач тіста', 12, 6, 'https://ibb.co/BBGCFyS');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Свинина', 1000, 120, 'https://ibb.co/Ntng950');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Смалець', 100, 7, 'https://ibb.co/0sctZWN');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сода', 300, 19, 'https://ibb.co/hsjqscs');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сухарики', 400, 123, 'https://ibb.co/grMLVPZ');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тимʼян', 60, 28, 'https://ibb.co/YNY3gty');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Томатна паста',460, 83, 'https://ibb.co/pJ4ySw7');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Фарш', 500, 89, 'https://ibb.co/yXdNfFC');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукор', 1000, 34, 'https://ibb.co/1Z7mwzk');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукрова пудра', 80, 19, 'https://ibb.co/Gd0BpPq');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорниця', 500, 177, 'https://ibb.co/CsCDFz4');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шампіньйони', 250, 42, 'https://ibb.co/3sNZjtw');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яловичина', 1000, 190, 'https://ibb.co/ZRjzq2B');

INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Хрін свіжий', 500, 180, 'https://ibb.co/HrB5Lpk');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чебрець', 230, 66, 'https://ibb.co/MDqYj0M');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Творог', 350, 54, 'https://ibb.co/101WK5C');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа манна', 550, 72, 'https://ibb.co/vQtn7qW');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оселедець', 500, 98, 'https://ibb.co/b2mBCSW');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яблука', 1000, 29, 'https://ibb.co/2vMBmzM');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мідії', 1000, 80, 'https://ibb.co/cDbN1r0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вино біле столове ', 750, 99, 'https://ibb.co/G2CvQgT');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Судак свіжий', 1000, 69, 'https://ibb.co/8r2BdJy');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Куркума', 300, 85, 'https://ibb.co/r6rBMmz');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лавровий лист', 20, 15, 'https://ibb.co/X2krRNs');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимон', 1000, 49, 'https://ibb.co/WpCZRxR');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кориця', 100, 34, 'https://ibb.co/9Y2ZWL7');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мускатний горіх', 10, 9, 'https://ibb.co/M6hcB7Y');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тісто листкове', 900, 68, 'https://ibb.co/KsxvdTL');


