--liquibase formatted sql
--changeset <Serhii Buria>:<add-data-table-products>
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Молоко', 850, 28, 'https://ibb.co/fd4LPS0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мята', 50, 48, 'https://ibb.co/kHr8fr0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Олія оливкова', 500, 132, 'https://ibb.co/QYsZyc0');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелений горох', 250, 228, 'https://ibb.co/FW1bH3x');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Базилік', 50, 48, 'https://ibb.co/0G6sYhB');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Дріжджі', 22, 21, 'https://ibb.co/0nBKKBh');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цибуля порей', 100, 18, 'https://ibb.co/Fms0SFT');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимонний сік', 200, 30, 'https://ibb.co/Mk7YXDZ');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шпроти', 190, 74, 'https://ibb.co/c8KNM5j');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оливи зелені без кісточок', 300, 62, 'https://ibb.co/y6FB9Fj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горіх волоський', 150, 169, 'https://ibb.co/vmtggVk');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорнослив', 250, 215, 'https://ibb.co/9pKxn8X');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Буряк', 500, 8, 'https://ibb.co/q1xBWkS');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа кукурудзяна', 1000, 16, 'https://ibb.co/V3sr59P');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бекон', 450, 140, 'https://ibb.co/f0qwyQv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бринза', 230, 54, 'https://ibb.co/7gF1jnV');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Апельсин', 1000, 50, 'https://ibb.co/vZNSp4r');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Бальзамічний оцет', 500, 139, 'https://ibb.co/M5FKFPh');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Баранина', 1000, 162, 'https://ibb.co/7YFvn4y');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Ванільний екстракт', 30, 160, 'https://ibb.co/Sm8p3t2');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершки 10%', 500, 40, 'https://ibb.co/vmMhg5X');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вершкове масло', 200, 58, 'https://ibb.co/xYKb6dm');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вишня (з кісточками)', 100, 55, 'https://ibb.co/hKgfBBr');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вода', 20, 80, 'https://ibb.co/myh70zK');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Гарбузове насіння', 500, 159, 'https://ibb.co/wBDLmBb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Горох', 900, 15, 'https://ibb.co/VHjsPP4');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Густий натуральний йогурт', 300, 25, 'https://ibb.co/JRhSGgv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень', 100, 74, 'https://ibb.co/KNM5Xrb');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Зелень (кріп)', 100, 64, 'https://ibb.co/F82kCKv');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Капуста', 1000, 22, 'https://ibb.co/6nXX65R');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Квашена капуста', 500, 46, 'https://ibb.co/WW5WVgf');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кисло-солодкий соус', 320, 126, 'https://ibb.co/WW5WVgf');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крохмаль', 230, 65,'https://ibb.co/hgnmHJy');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Малина', 500, 98, 'https://ibb.co/0cnLzGz');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мед', 500, 116, 'https://ibb.co/jgLC52T');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Морква', 1000, 60, 'https://ibb.co/NLHDxgj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мясо ягняти', 1000, 160, 'https://ibb.co/2hcfxFV');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Насіння льону', 100, 9, 'https://ibb.co/LRtcQRj');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Огірки', 1000, 109, 'https://i.ibb.co/XJKQLbw/d8c445f1-5ce6-11e9-b2d2-000c2974779c.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оцет', 1000, 29, 'https://i.ibb.co/68rhjMh/02f158b0-6498-11eb-ac63-772bd181f15b-jpg.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Паста', 500, 51, 'https://i.ibb.co/yW2StKk/izdeliya-makaronnye-la-pasta-perfetto-stortelli.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець солодкий', 1000, 230, 'https://i.ibb.co/tDhh7mm/Bell-Peppers.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Перець чилі', 100, 34, 'https://i.ibb.co/MnQxDdp/2023-04-20-20-07.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Полуниця', 250, 50, 'https://i.ibb.co/n1C3Yp1/klubnika-egipet-73107014367685.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Помідори', 1000, 77, 'https://i.ibb.co/7nFSS4S/image-of-hot-house-red-cluster-tomatoes-fruit-14764460834860-600x600.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Пшоно', 1000, 27, 'https://i.ibb.co/j4sBV0B/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Рис', 800, 79, 'https://i.ibb.co/3Tm1sk4/2023-04-20-19-58.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розмарин', 70, 32, 'https://i.ibb.co/2cP5VKQ/4088600212500-0.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Розпушувач тіста', 12, 6, 'https://i.ibb.co/njBLt75/49001-003.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Свинина', 1000, 120, 'https://i.ibb.co/LYhDxmT/marbled-pig-meat-pork-loin-slices.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Смалець', 100, 7, 'https://i.ibb.co/NTsSpkh/smalec-spichlerz-rusiecki-staropolskij-s-myasom.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сода', 300, 19, 'https://i.ibb.co/LSWGSrS/soda-pishchevaya-04kg-ukraina0-1.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Сухарики', 400, 123, 'https://i.ibb.co/K5jpwLx/68f1b009.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тимʼян', 60, 28, 'https://i.ibb.co/rQTm9Zc/2023-04-20-19-10-1.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Томатна паста',460, 83, 'https://i.ibb.co/bzNJkm0/tomatna-pata.png');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Фарш', 500, 89, 'https://i.ibb.co/pxb10jT/GF-Mince-Beef-web1.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукор', 1000, 34, 'https://i.ibb.co/dBj5zmR/catalog-product-main-18505.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Цукрова пудра', 80, 19, 'https://i.ibb.co/nwbZmkF/ae4c3ed8-bae9-11ec-ad16-000c2974779c-912x804-f.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чорниця', 500, 177, 'https://i.ibb.co/wrGj1R8/95a21fc78dcdc137c3b75bc8bfb3461c.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Шампіньйони', 250, 42, 'https://i.ibb.co/cvFnZzP/shampwhite.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яловичина', 1000, 190, 'https://i.ibb.co/mrj5fN9/4d7a829c-7d28-11e9-af5f-000c2974779c-912x804-f.jpg');

INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Хрін свіжий', 500, 180, 'https://i.ibb.co/YtPH4Tq/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Чебрець', 230, 66, 'https://i.ibb.co/Y7vzKsp/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Творог', 350, 54, 'https://i.ibb.co/tHgrct0/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Крупа манна', 550, 72, 'https://i.ibb.co/1dSWDQN/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Оселедець', 500, 98, 'https://i.ibb.co/Tb287Vv/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Яблука', 1000, 29, 'https://i.ibb.co/y6kJGzk/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мідії', 1000, 80, 'https://i.ibb.co/jgVLTrm/2.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Вино біле столове ', 750, 99, 'https://i.ibb.co/cF2chzL/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Судак свіжий', 1000, 69, 'https://i.ibb.co/v3mBQbN/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Куркума', 300, 85, 'https://i.ibb.co/Kqvt7Xf/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лавровий лист', 20, 15, 'https://i.ibb.co/smJdYkw/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Лимон', 1000, 49, 'https://i.ibb.co/3YK2PrP/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Кориця', 100, 34, 'https://i.ibb.co/XJpYtgq/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Мускатний горіх', 10, 9, 'https://i.ibb.co/KwG2KWM/image.jpg');
INSERT INTO products (product_name, amount_in_package, price, image_Url) VALUES ('Тісто листкове', 900, 68, 'https://i.ibb.co/my5WkfX/image.jpg');


